### ISSUE TITLE
ErrorListener invoked when closing connection.

### ISSUE THREAD

**Issue by guusdk** [nats-io/java-nats-streaming#114]
When closing a Streaming Connection using `io.nats.streaming.StreamingConnection#close`, `io.nats.client.ErrorListener#exceptionOccurred` is invoked when an Error Listener has been registered. The following stack trace is reported:
  
    java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at io.nats.client.impl.SocketDataPort.read(SocketDataPort.java:94)
        at io.nats.client.impl.NatsConnectionReader.run(NatsConnectionReader.java:112)
        at java.lang.Thread.run(Thread.java:748)

As the connection is being closed, the socket being closed should not be considered an error.

**Comment by sasbury** [comment]
This should be fixed in 2.4.2 of the underlying nats library.
