### ISSUE TITLE
Protobuf released incompatible version

### ISSUE THREAD

**Issue by moleksyuk** [nats-io/java-nats-streaming#121]
Hi guys,

Due to dynamic versioning dependency to protobuf 
https://github.com/nats-io/java-nats-streaming/blob/8c7793ee5c188cef726cdfa16249dc0b74b3fc25/build.gradle#L55

I've got issue:
```java
Exception in thread "main" java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class io.nats.streaming.protobuf.ConnectRequest
	at io.nats.streaming.protobuf.ConnectRequest.getSerializedSize(ConnectRequest.java:204)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:64)
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:152)
	at io.nats.streaming.StreamingConnectionFactory.createConnection(StreamingConnectionFactory.java:59)
	at com.mycompany.push.NatsMessagePusher.<init>(NatsMessagePusher.java:25)
	at com.mycompany.push.NatsMessagePusher.main(NatsMessagePusher.java:61)
```

Current version of protobuf: [3.7.0-rc1](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java)

P.S. Any plans to avoid dymaic versions for dependecies as it's a bad practice?

**Comment by sasbury** [comment]
What version should we set it to, I will lock it down on the next release.

**Comment by moleksyuk** [comment]
@sasbury works fine with version 3.6.1
