### ISSUE TITLE
Different nats_checkstyle.xml file contents (vs. jnats-0.5.1)

### ISSUE THREAD

**Issue by laugimethods** [nats-io/java-nats-streaming#19]
While calling `sbt clean assembly dockerFileTask` against [docker-nats-connector-spark/app](https://github.com/Logimethods/docker-nats-connector-spark/tree/master/app), I get such fatal exception:
```
[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/Users/laugimethods/.ivy2/cache/io.nats/java-nats-streaming/bundles/java-nats-streaming-0.1.1.jar:nats_checkstyle.xml
/Users/laugimethods/.ivy2/cache/io.nats/jnats/bundles/jnats-0.5.1.jar:nats_checkstyle.xml
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /Users/laugimethods/.ivy2/cache/io.nats/java-nats-streaming/bundles/java-nats-streaming-0.1.1.jar:nats_checkstyle.xml
[error] /Users/laugimethods/.ivy2/cache/io.nats/jnats/bundles/jnats-0.5.1.jar:nats_checkstyle.xml
```
Indeed, [jnats-0.5.1.jar/!/nats_checkstyle.xml](https://oss.sonatype.org/service/local/repositories/releases/archive/io/nats/jnats/0.5.1/jnats-0.5.1.jar/!/nats_checkstyle.xml) has (at least) the following module commented:
```
</module>
<!--

        <module name="CatchParameterName">
            <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
            <message key="name.invalidPattern"
             value="Catch parameter name ''{0}'' must match pattern ''{1}''."/>
        </module>
-->
<module name="LocalVariableName">
```
which is not the case for [java-nats-streaming-0.1.1.jar/!/nats_checkstyle.xml](https://oss.sonatype.org/service/local/repositories/releases/archive/io/nats/java-nats-streaming/0.1.1/java-nats-streaming-0.1.1.jar/!/nats_checkstyle.xml).

**Comment by laugimethods** [comment]
FYI, that issue has been solved that way (code added to the `build.sbt` file):
```
// @see http://stackoverflow.com/questions/30446984/spark-sbt-assembly-deduplicate-different-file-contents-found-in-the-followi
assemblyMergeStrategy in assembly := {
    case "nats_checkstyle.xml" => MergeStrategy.last
    case x =>
        val oldStrategy = (assemblyMergeStrategy in assembly).value
        oldStrategy(x)
}
```

**Comment by mcqueary** [comment]
Laurent -- interesting. This is probably the result of not filtering the files that go into the bundle(s). I don't believe that `nats_checkstyle.xml` should be in there (nor any other non-runtime resources). I'll fix that. Thanks for making me aware of this.

**Comment by mcqueary** [comment]
`java-nats-streaming-0.1.2`, which depends on `jnats-0.5.3` has been released and fixes this altogether by removing `nats_checkstyle.xml` from the bundle/jar of both packages. Give it a while to show up on Central, as always.
