### ISSUE TITLE
Blank username and password causes ConcurrentModificationException

### ISSUE THREAD

**Issue by jebbench** [nats-io/java-nats-streaming#73]
When creating a connection to a secure NATs cluster and forgetting to provide a username and password we get a ConcurrentModificationException.

Our ocnfiguration:
clientId: "myhost-dev-646597838-fx82p"
clusterId: "my-cluster-id"
password: ""
username: ""
secure: true
servers: ["nats://my-cluster.nats.cloud:4222","nats://my-cluster.nats.cloud:4222"]

Client driver version is 0.5.0.

```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:407)
	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:220)
	at work.faber.eventstream.NatsConnectionBuilder.getConnection(NatsConnectionBuilder.java:108)
	at work.faber.eventstream.NatsClient.connect(NatsClient.java:170)
	at work.faber.eventstream.NatsClient.<init>(NatsClient.java:70)
	at work.faber.suggestion.service.MainVerticle.start(MainVerticle.java:57)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:407)
	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:220)
```

**Comment by ColinSullivan1** [comment]
Thank you for letting us know, we'll take a look.

**Comment by sasbury** [comment]
Are you still seeing this in the latest release?

**Comment by sasbury** [comment]
closing as out of date, let me know if you see something similar in the latest release.
