### ISSUE TITLE
Request timing out with NATS Streaming 0.9

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/java-nats-streaming#83]
I am getting request timed out when I am using the current Java library with NATS Streaming 0.9.

This is the exception trace:

```
java.io.IOException: stan: connect request timeout
2018-03-18 19:59:23,184 [ERROR] [Logger::c.p.u.s.NatsProvider] [Thread::main]  - IOException occurred while creating NATS Connection::java.io.IOException: stan: connect request timeout
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:127)
2018-03-18 19:59:23,184 [ERROR] [Logger::c.p.u.s.NatsProvider] [Thread::main]  - NATS Connection failure occurred
	at io.nats.streaming.NatsStreaming.connect(NatsStreaming.java:83)

```
This is the code I am using from the example

```
                String natsUrl = "nats://localhost:4222";
		Options opts = NatsStreaming.defaultOptions();
		if (natsUrl != null) {
			opts = new Options.Builder().natsUrl(natsUrl).build();
		}
		streamingConnection = null;

		try {
			streamingConnection = NatsStreaming.connect("cluster", environmentConfig.getProperty(Server.instance), opts);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("IOException occurred while creating NATS Connection::" + e);
		}

```

**Comment by sachinwalia2k8** [comment]
Upon spending some time with debugger on I find the following piece of code that is causing the issue. 

This is part of **io.nats.client.ConnectionImpl**.

In particular 

                **response = (Message)queue.poll(timeout, unit);**
If nothing is added to this Blocking Queue than it'll always return head as null so the exception thrown is valid. 

Can someone from Nats team please confirm this?


```
            this.createRespMux();
            BlockingQueue<Message> queue = new ArrayBlockingQueue(1);
            String respInbox = this.newRespInbox();
            String token = this.respToken(respInbox);
            this.respMap.put(token, queue);
            this.publish(subject, respInbox, data);
            Message response;
            if (timeout < 0L) {
                response = (Message)queue.take();
            } else {
                **response = (Message)queue.poll(timeout, unit);**
                if (response == null) {
                    this.respMap.remove(token);
                }
            }

            return response;

```

**Comment by sachinwalia2k8** [comment]
Turned out to be my mistake where clusterId was incorrectly specified. Closing ticket.
