### ISSUE TITLE
NullPointerException on Subscription::close method

### ISSUE THREAD

**Issue by tkgreg** [nats-io/java-nats-streaming#86]
I'm trying to play around with nats-streaming and I took an example from the readme but it throws a NullPointerException when I try to call `sub.close()`

```
Exception in thread "main" java.lang.NullPointerException
	at shaded.nats.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at shaded.nats.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
	at shaded.nats.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.nats.streaming.protobuf.SubscriptionResponse.parseFrom(SubscriptionResponse.java:253)
	at io.nats.streaming.SubscriptionImpl.close(SubscriptionImpl.java:178)
	at NatsStreamingService.main(NatsStreamingService.java:41)
```

```
import io.nats.streaming.*;

import java.time.Duration;
import java.util.concurrent.CountDownLatch;

public class NatsStreamingService {


    public static void main(String[] args) throws Exception {

        // Create a connection factory
        StreamingConnectionFactory cf = new StreamingConnectionFactory("test-cluster", "bar");
        cf.setNatsUrl("nats://localhost:4223");

        try (StreamingConnection sc = cf.createConnection()) {
            sc.publish("TestSubject", "Hello World".getBytes());

            final CountDownLatch doneSignal = new CountDownLatch(1);

            final SubscriptionOptions options = new SubscriptionOptions.Builder()
                .deliverAllAvailable()
                .manualAcks()
                .ackWait(Duration.ofSeconds(60L))
                .build();

            Subscription sub = sc.subscribe("TestSubject", m -> {
                System.out.printf("Received a message: %s\n", new String(m.getData()));
                try {
                    System.out.println("Going to ack");
                    m.ack();
                    doneSignal.countDown();
                }catch (Exception e) {
                    e.printStackTrace();
                }
            }, options);

            doneSignal.await();

            sub.close(true);
        }

    }

}
```

Client version: 0.5.0
Server version: 0.9.2

**Comment by sasbury** [comment]
Haven't had a chance to test this on 2.0.1, if you beat me please update this issue.

**Comment by sasbury** [comment]
I got a chance to try this code on 2.0.2 and don't see any exceptions. Can you give it a try when you get a chance. Closing for now, reopen if you can reproduce.
